// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fit2way_
NumericVector fit2way_(const NumericVector& tab1, const NumericVector& tab2, const CharacterVector& R, const CharacterVector& vn);
RcppExport SEXP _gRim_fit2way_(SEXP tab1SEXP, SEXP tab2SEXP, SEXP RSEXP, SEXP vnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type tab1(tab1SEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type tab2(tab2SEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type vn(vnSEXP);
    rcpp_result_gen = Rcpp::wrap(fit2way_(tab1, tab2, R, vn));
    return rcpp_result_gen;
END_RCPP
}
// parm_ghk2pms_
List parm_ghk2pms_(List parms);
RcppExport SEXP _gRim_parm_ghk2pms_(SEXP parmsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type parms(parmsSEXP);
    rcpp_result_gen = Rcpp::wrap(parm_ghk2pms_(parms));
    return rcpp_result_gen;
END_RCPP
}
// C_pms2ghk
RcppExport SEXP C_pms2ghk(SEXP parms_);
RcppExport SEXP _gRim_C_pms2ghk(SEXP parms_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type parms_(parms_SEXP);
    rcpp_result_gen = Rcpp::wrap(C_pms2ghk(parms_));
    return rcpp_result_gen;
END_RCPP
}
// C_ghk2pms
RcppExport SEXP C_ghk2pms(SEXP parms_);
RcppExport SEXP _gRim_C_ghk2pms(SEXP parms_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type parms_(parms_SEXP);
    rcpp_result_gen = Rcpp::wrap(C_ghk2pms(parms_));
    return rcpp_result_gen;
END_RCPP
}
// parm_normalize_ghk_
List parm_normalize_ghk_(List parms);
RcppExport SEXP _gRim_parm_normalize_ghk_(SEXP parmsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type parms(parmsSEXP);
    rcpp_result_gen = Rcpp::wrap(parm_normalize_ghk_(parms));
    return rcpp_result_gen;
END_RCPP
}
