# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit2way_ <- function(tab1, tab2, R, vn) {
    .Call('_gRim_fit2way_', PACKAGE = 'gRim', tab1, tab2, R, vn)
}

parm_ghk2pms_ <- function(parms) {
    .Call('_gRim_parm_ghk2pms_', PACKAGE = 'gRim', parms)
}

C_pms2ghk <- function(parms_) {
    .Call('_gRim_C_pms2ghk', PACKAGE = 'gRim', parms_)
}

C_ghk2pms <- function(parms_) {
    .Call('_gRim_C_ghk2pms', PACKAGE = 'gRim', parms_)
}

parm_normalize_ghk_ <- function(parms) {
    .Call('_gRim_parm_normalize_ghk_', PACKAGE = 'gRim', parms)
}

