# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit2way_ <- function(tab1, tab2, R, vn) {
    .Call('_gRim_fit2way_', PACKAGE = 'gRim', tab1, tab2, R, vn)
}

ghk2pmsParms_ <- function(parms) {
    .Call('_gRim_ghk2pmsParms_', PACKAGE = 'gRim', parms)
}

pms2ghkParms_ <- function(parms) {
    .Call('_gRim_pms2ghkParms_', PACKAGE = 'gRim', parms)
}

updateA <- function(A, E, row, col) {
    .Call('_gRim_updateA', PACKAGE = 'gRim', A, E, row, col)
}

update_ghkParms_ <- function(Cparms, dgen_idx, cgen_idx, ghk_obs, pms_obs, ghk_fit, pms_fit, scale, details = 0) {
    .Call('_gRim_update_ghkParms_', PACKAGE = 'gRim', Cparms, dgen_idx, cgen_idx, ghk_obs, pms_obs, ghk_fit, pms_fit, scale, details)
}

C_pms2ghk <- function(parms_) {
    .Call('_gRim_C_pms2ghk', PACKAGE = 'gRim', parms_)
}

C_ghk2pms <- function(parms_) {
    .Call('_gRim_C_ghk2pms', PACKAGE = 'gRim', parms_)
}

normalize_ghkParms_ <- function(parms) {
    .Call('_gRim_normalize_ghkParms_', PACKAGE = 'gRim', parms)
}

